-- Add followup_questions and followup_answers columns to user table
-- This migration script adds support for the follow-up questions feature

ALTER TABLE "user" 
ADD COLUMN IF NOT EXISTS followup_questions TEXT,
ADD COLUMN IF NOT EXISTS followup_answers TEXT;

-- Add comments for documentation
COMMENT ON COLUMN "user".followup_questions IS 'JSON string of follow-up questions generated by LLM (for Type B and C users)';
COMMENT ON COLUMN "user".followup_answers IS 'User''s answers to follow-up questions (for Type C users)';

