-- Complete migration for the new follow-up questions feature
-- Execute this in Supabase SQL Editor

-- Step 1: Add followup_questions and followup_answers columns
ALTER TABLE "user" 
ADD COLUMN IF NOT EXISTS followup_questions TEXT,
ADD COLUMN IF NOT EXISTS followup_answers TEXT;

-- Step 2: Remove details column (no longer used)
ALTER TABLE "user" 
DROP COLUMN IF EXISTS details;

-- Comments for documentation
COMMENT ON COLUMN "user".followup_questions IS 'JSON string of follow-up questions generated by LLM (for Type B and C users)';
COMMENT ON COLUMN "user".followup_answers IS 'User''s answers to follow-up questions (stored for both Type B and C, but only used in recommendations for Type C)';

-- Verify changes
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'user' 
ORDER BY ordinal_position;

